server:
  servlet:
    port: 8080
    contextPath: /api

spring:

  application:
    name: movieapp-api

  datasource:
    url: jdbc:postgresql://mydbinstance.cfpm0m1wprxx.us-east-1.rds.amazonaws.com:5432/moviedb
    username: movieapp
    password: postgres

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
